language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: "pip install -e .[test]"
script:
  - pytest --cov=carrera
after_success:
  coveralls
